import { MigrationInterface, QueryRunner } from "typeorm";

export class AddSubtasksAndRecurrence1780450225771 implements MigrationInterface {
    name = 'AddSubtasksAndRecurrence1780450225771'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "tasks_project_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "tasks_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "projects_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "refresh_tokens_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "task_history" DROP CONSTRAINT "task_history_task_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "user_settings" DROP CONSTRAINT "user_settings_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "task_templates" DROP CONSTRAINT "task_templates_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "task_links" DROP CONSTRAINT "task_links_source_task_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "task_links" DROP CONSTRAINT "task_links_target_task_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "project_files" DROP CONSTRAINT "project_files_project_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "notes" DROP CONSTRAINT "notes_user_id_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tasks_project_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tasks_due_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tasks_reminder_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tasks_user_inbox"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tasks_scheduled_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_projects_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notes_user_id"`);
        await queryRunner.query(`ALTER TABLE "task_links" DROP CONSTRAINT "task_links_source_task_id_target_task_id_key"`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "parent_task_id" uuid`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "recurrence" jsonb`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "recurrence_parent_id" uuid`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "recurrence_date" date`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "is_inbox" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "priority" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "reminder_sent" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "estimated_minutes" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "time_spent_seconds" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "projects" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "projects" ALTER COLUMN "status" SET DEFAULT 'not_started'`);
        await queryRunner.query(`ALTER TABLE "projects" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "projects" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "task_history" ALTER COLUMN "changed_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "task_history" ALTER COLUMN "changed_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_settings" ALTER COLUMN "daily_briefing_time" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_settings" ALTER COLUMN "daily_briefing_enabled" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_settings" ALTER COLUMN "weekly_review_enabled" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_settings" ALTER COLUMN "weekly_review_day" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_settings" ALTER COLUMN "weekly_review_time" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_settings" DROP COLUMN "timezone"`);
        await queryRunner.query(`ALTER TABLE "user_settings" ADD "timezone" character varying NOT NULL DEFAULT 'Europe/Paris'`);
        await queryRunner.query(`ALTER TABLE "user_settings" ALTER COLUMN "preferences" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "user_settings" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "task_templates" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "project_files" DROP COLUMN "drive_file_id"`);
        await queryRunner.query(`ALTER TABLE "project_files" ADD "drive_file_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "project_files" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "project_files" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "project_files" DROP COLUMN "mime_type"`);
        await queryRunner.query(`ALTER TABLE "project_files" ADD "mime_type" character varying`);
        await queryRunner.query(`ALTER TABLE "project_files" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notes" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notes" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "task_links" ADD CONSTRAINT "UQ_4307522673f624b9a71ac24cc41" UNIQUE ("source_task_id", "target_task_id")`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_db55af84c226af9dce09487b61b" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_9eecdb5b1ed8c7c2a1b392c28d4" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_54fc42a253a8338488ec1f960ad" FOREIGN KEY ("parent_task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_8aacfa08824e0675446f6f1a53f" FOREIGN KEY ("recurrence_parent_id") REFERENCES "tasks"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_bd55b203eb9f92b0c8390380010" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_history" ADD CONSTRAINT "FK_e733285140c013322a9ae1be644" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_settings" ADD CONSTRAINT "FK_4ed056b9344e6f7d8d46ec4b302" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_templates" ADD CONSTRAINT "FK_8458278105f61621f0f90528fbe" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_links" ADD CONSTRAINT "FK_0bf64debbc059dcf4601f9071dd" FOREIGN KEY ("source_task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_links" ADD CONSTRAINT "FK_3b5f444d217f9afc0c21d5df9f9" FOREIGN KEY ("target_task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notes" ADD CONSTRAINT "FK_7708dcb62ff332f0eaf9f0743a7" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "notes" DROP CONSTRAINT "FK_7708dcb62ff332f0eaf9f0743a7"`);
        await queryRunner.query(`ALTER TABLE "task_links" DROP CONSTRAINT "FK_3b5f444d217f9afc0c21d5df9f9"`);
        await queryRunner.query(`ALTER TABLE "task_links" DROP CONSTRAINT "FK_0bf64debbc059dcf4601f9071dd"`);
        await queryRunner.query(`ALTER TABLE "task_templates" DROP CONSTRAINT "FK_8458278105f61621f0f90528fbe"`);
        await queryRunner.query(`ALTER TABLE "user_settings" DROP CONSTRAINT "FK_4ed056b9344e6f7d8d46ec4b302"`);
        await queryRunner.query(`ALTER TABLE "task_history" DROP CONSTRAINT "FK_e733285140c013322a9ae1be644"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_bd55b203eb9f92b0c8390380010"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_8aacfa08824e0675446f6f1a53f"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_54fc42a253a8338488ec1f960ad"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_9eecdb5b1ed8c7c2a1b392c28d4"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_db55af84c226af9dce09487b61b"`);
        await queryRunner.query(`ALTER TABLE "task_links" DROP CONSTRAINT "UQ_4307522673f624b9a71ac24cc41"`);
        await queryRunner.query(`ALTER TABLE "notes" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notes" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "project_files" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "project_files" DROP COLUMN "mime_type"`);
        await queryRunner.query(`ALTER TABLE "project_files" ADD "mime_type" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "project_files" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "project_files" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "project_files" DROP COLUMN "drive_file_id"`);
        await queryRunner.query(`ALTER TABLE "project_files" ADD "drive_file_id" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "task_templates" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_settings" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_settings" ALTER COLUMN "preferences" SET DEFAULT '{"ai": {"model": "meta/llama-3.1-70b-instruct", "modelCode": "nvidia/llama-3.1-nemotron-70b-instruct", "streaming": true, "temperature": 0.7}, "email": {"enabled": true, "reminders": true, "milestones": true, "weeklyReviewDay": 0, "weeklyReviewTime": "19:00", "dailyBriefingTime": "08:00"}, "desktop": {"enabled": true, "reminders": true, "milestones": true, "dailyBriefing": true, "overdueAlerts": true}}'`);
        await queryRunner.query(`ALTER TABLE "user_settings" DROP COLUMN "timezone"`);
        await queryRunner.query(`ALTER TABLE "user_settings" ADD "timezone" character varying(50) DEFAULT 'Europe/Paris'`);
        await queryRunner.query(`ALTER TABLE "user_settings" ALTER COLUMN "weekly_review_time" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_settings" ALTER COLUMN "weekly_review_day" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_settings" ALTER COLUMN "weekly_review_enabled" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_settings" ALTER COLUMN "daily_briefing_enabled" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_settings" ALTER COLUMN "daily_briefing_time" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "task_history" ALTER COLUMN "changed_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "task_history" ALTER COLUMN "changed_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "projects" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "projects" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "projects" ALTER COLUMN "status" SET DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE "projects" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "time_spent_seconds" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "estimated_minutes" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "reminder_sent" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "priority" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "is_inbox" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "recurrence_date"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "recurrence_parent_id"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "recurrence"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "parent_task_id"`);
        await queryRunner.query(`ALTER TABLE "task_links" ADD CONSTRAINT "task_links_source_task_id_target_task_id_key" UNIQUE ("source_task_id", "target_task_id")`);
        await queryRunner.query(`CREATE INDEX "idx_notes_user_id" ON "notes" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_projects_user_id" ON "projects" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_tasks_scheduled_at" ON "tasks" ("scheduled_at") `);
        await queryRunner.query(`CREATE INDEX "idx_tasks_user_inbox" ON "tasks" ("user_id", "is_inbox") `);
        await queryRunner.query(`CREATE INDEX "idx_tasks_reminder_at" ON "tasks" ("reminder_at") WHERE (reminder_sent = false)`);
        await queryRunner.query(`CREATE INDEX "idx_tasks_due_date" ON "tasks" ("due_date") `);
        await queryRunner.query(`CREATE INDEX "idx_tasks_project_id" ON "tasks" ("project_id") `);
        await queryRunner.query(`ALTER TABLE "notes" ADD CONSTRAINT "notes_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_files" ADD CONSTRAINT "project_files_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_links" ADD CONSTRAINT "task_links_target_task_id_fkey" FOREIGN KEY ("target_task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_links" ADD CONSTRAINT "task_links_source_task_id_fkey" FOREIGN KEY ("source_task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_templates" ADD CONSTRAINT "task_templates_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_settings" ADD CONSTRAINT "user_settings_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_history" ADD CONSTRAINT "task_history_task_id_fkey" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "refresh_tokens_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "projects_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "tasks_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "tasks_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
